name: Test and Release

on:
  push:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  tests:
    runs-on: ubuntu-latest

    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci --no-audit

      - name: Compile TypeScript
        run: npx tsc

      - name: Check source code with eslint
        run: npx eslint ./

      - name: Check if source code is properly formatted
        run: npx prettier -c ./

      - name: Run tests
        run: npm test

      - name: Ensure it builds
        env:
          REGISTRY_ENDPOINT: ${{ vars.REGISTRY_ENDPOINT }}
        run: |
          npm run build

  e2e-tests:
    timeout-minutes: 10

    runs-on: ubuntu-latest

    environment: production

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        env:
          MAP_REGION: ${{ vars.MAP_REGION }}
          MAP_NAME: ${{ vars.MAP_NAME }}
          MAP_API_KEY: ${{ vars.MAP_API_KEY }}
        run: npm run test:e2e

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

  release:
    if: github.ref == 'refs/heads/saga'

    needs:
      - tests
      - e2e-tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"

      - name: Semantic release
        continue-on-error: true
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger deployment workflow
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run deploy.yaml
